In [7]:
import numpy as np
from sklearn.model_selection import train_test_split

# RAF DB Dataset

## Status: Done

In [8]:
X = np.load("/run/media/viper/LSP/Dataset/RAF-DB/basic/numpy/X_aligned.npy")
Y = np.load("/run/media/viper/LSP/Dataset/RAF-DB/basic/numpy/Y_aligned.npy")

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.5, random_state=42)

In [10]:
print(y_train.shape)
print(y_test.shape)
print(y_val.shape)

(12271, 7)
(1534, 7)
(1534, 7)


In [12]:
np.sum(y_train, axis=0)

array([1294,  286,  690, 4782, 1991,  698, 2530], dtype=uint64)

In [13]:
np.sum(y_test, axis=0)

array([183,  33,  90, 576, 242,  87, 323], dtype=uint64)

In [14]:
np.sum(y_val, axis=0)

array([142,  36,  97, 599, 227,  82, 351], dtype=uint64)

In [16]:
np.save("/run/media/viper/LSP/Dataset/RAF-DB/basic/shuffled/X_train_shuffled.npy", X_train, allow_pickle=True)
np.save("/run/media/viper/LSP/Dataset/RAF-DB/basic/shuffled/X_test_shuffled.npy", X_test, allow_pickle=True)
np.save("/run/media/viper/LSP/Dataset/RAF-DB/basic/shuffled/X_val_shuffled.npy", X_val, allow_pickle=True)
np.save("/run/media/viper/LSP/Dataset/RAF-DB/basic/shuffled/Y_train_shuffled.npy", y_train, allow_pickle=True)
np.save("/run/media/viper/LSP/Dataset/RAF-DB/basic/shuffled/Y_test_shuffled.npy", y_test, allow_pickle=True)
np.save("/run/media/viper/LSP/Dataset/RAF-DB/basic/shuffled/Y_val_shuffled.npy", y_val, allow_pickle=True)