In [1]:
import torch

In [3]:
data = torch.rand(10, 7)
data

tensor([[0.5016, 0.7027, 0.2542, 0.2365, 0.6479, 0.3096, 0.2230],
        [0.8977, 0.9135, 0.5876, 0.7326, 0.6935, 0.2132, 0.7078],
        [0.8794, 0.8340, 0.7807, 0.9565, 0.7590, 0.2468, 0.9988],
        [0.3965, 0.9190, 0.2976, 0.5702, 0.2690, 0.3867, 0.1107],
        [0.6170, 0.3694, 0.4481, 0.1787, 0.8853, 0.4054, 0.0816],
        [0.6692, 0.4387, 0.5855, 0.1227, 0.0805, 0.7625, 0.7805],
        [0.3787, 0.7994, 0.8964, 0.5810, 0.5757, 0.3995, 0.5975],
        [0.2325, 0.1009, 0.1804, 0.8361, 0.3628, 0.5039, 0.8535],
        [0.4450, 0.9370, 0.5283, 0.6670, 0.5601, 0.9910, 0.4048],
        [0.2481, 0.6923, 0.5453, 0.1777, 0.7386, 0.7889, 0.4314]])

In [4]:
v = data.argmax(dim=1)
v

tensor([1, 1, 6, 1, 4, 6, 2, 6, 5, 5])

In [6]:
torch.zeros(data.shape).scatter(1, v.unsqueeze (1), 1.0)

tensor([[0., 1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1., 0.]])